FROM golang:1.26-alpine AS backend-build

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app/
COPY ./go.mod ./go.sum ./
RUN go mod download
COPY cmd/ ./cmd

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/releases.bin ./cmd/releases/

EXPOSE 8033
ENV TZ=Europe/Warsaw

CMD ["./releases.bin"]
