FROM golang:1.26-alpine AS backend-build

RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app/
COPY ./go.mod ./go.sum ./
RUN go mod download
COPY cmd/ ./cmd

RUN CGO_ENABLED=0 GOOS=linux go build -o /app/proxy.bin ./cmd/proxy/

EXPOSE 8031
ENV TZ=Europe/Warsaw

CMD ["./proxy.bin"]
